figure(6);
if ~isoctave;set(gcf,'Position',[300,200,scrSz(3)/3,scrSz(4)/2]);end
subplot(211);
plot(eta(:,2), eta(:,1));
hold on;
plot(wpt.pos.y, wpt.pos.x, 'rx', 'MarkerSize', 10);
hold off;
xlabel('East');
ylabel('North');
title('North-East plot (m)');
xlim([0, 2500]);
axis('equal');
grid on;
subplot(212);
plot(eta(:,2), eta(:,3));
hold on;
plot(wpt.pos.y, wpt.pos.z, 'rx', 'MarkerSize', 10);
hold off;
xlim([0, 2500]);
ylim([0, 150]);
xlabel('East');
ylabel('Down');
title('Down-East plot (m)');
grid on;
legend('Actual path', 'Waypoints', 'Location', legendLocation);
set(findall(gcf, 'type', 'line'), 'LineWidth', 2);
set(findall(gcf, 'type', 'text'), 'FontSize', 14);
set(findall(gcf, 'type', 'legend'), 'FontSize', legendSize);